name: Java Gradle

on: [push]

jobs:
  Despliegue:

    - uses: actions/checkout@v4    
    - name: Despliegue al servidor AWS
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}

    - name: Ejecución cmd en AWS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd /home/ubuntu/java_hello
          gradle bootJar
          sudo systemctl restart api.service